"""Create ChanAnalyzer v2 normalized schema

Revision ID: 0001_v2_schema
Revises: 
Create Date: 2026-07-28 17:19:29.095186
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001_v2_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('job_kind', sa.String(length=64), nullable=False),
    sa.Column('cron_expression', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=True)
    op.create_table('trading_calendar',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('trade_date', 'exchange')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('range_start', sa.Date(), nullable=True),
    sa.Column('range_end', sa.Date(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_kind'), 'ingestion_runs', ['kind'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_area'), 'instruments', ['area'], unique=False)
    op.create_index(op.f('ix_instruments_code'), 'instruments', ['code'], unique=True)
    op.create_index(op.f('ix_instruments_exchange'), 'instruments', ['exchange'], unique=False)
    op.create_index(op.f('ix_instruments_industry_id'), 'instruments', ['industry_id'], unique=False)
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=False)
    op.create_index(op.f('ix_instruments_status'), 'instruments', ['status'], unique=False)
    op.create_index(op.f('ix_instruments_ts_code'), 'instruments', ['ts_code'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_active_dedupe', 'jobs', ['dedupe_key', 'status'], unique=False)
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_dedupe_key'), 'jobs', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_requested_by'), 'jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('secret_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlist_user_name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=12), nullable=False),
    sa.Column('adjustment', sa.String(length=12), nullable=False),
    sa.Column('bar_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('quality_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('high >= low', name='ck_bars_high_low'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'adjustment', 'bar_time', name='uq_bars_series_time')
    )
    op.create_index('ix_bars_series_time', 'bars', ['instrument_id', 'timeframe', 'adjustment', 'bar_time'], unique=False)
    op.create_table('ipo_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('legacy_code', sa.String(length=16), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=False),
    sa.Column('issue_price', sa.Float(), nullable=True),
    sa.Column('issue_pe', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_date', 'legacy_code', name='uq_ipo_date_code')
    )
    op.create_index(op.f('ix_ipo_events_instrument_id'), 'ipo_events', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_ipo_events_legacy_code'), 'ipo_events', ['legacy_code'], unique=False)
    op.create_index(op.f('ix_ipo_events_listing_date'), 'ipo_events', ['listing_date'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'sequence', name='uq_job_event_sequence')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('job_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('subject_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'subject_key', name='uq_job_item_subject')
    )
    op.create_index(op.f('ix_job_items_job_id'), 'job_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_items_status'), 'job_items', ['status'], unique=False)
    op.create_table('limit_up_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('legacy_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('consecutive_boards', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'legacy_code', name='uq_limit_up_date_code')
    )
    op.create_index(op.f('ix_limit_up_events_instrument_id'), 'limit_up_events', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_limit_up_events_legacy_code'), 'limit_up_events', ['legacy_code'], unique=False)
    op.create_index(op.f('ix_limit_up_events_quarantined'), 'limit_up_events', ['quarantined'], unique=False)
    op.create_index(op.f('ix_limit_up_events_trade_date'), 'limit_up_events', ['trade_date'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('scan_kind', sa.String(length=32), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=True),
    sa.Column('signal_date', sa.Date(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_instrument_id'), 'scan_results', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_scan_results_job_id'), 'scan_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_kind'), 'scan_results', ['scan_kind'], unique=False)
    op.create_index(op.f('ix_scan_results_signal_date'), 'scan_results', ['signal_date'], unique=False)
    op.create_index(op.f('ix_scan_results_signal_type'), 'scan_results', ['signal_type'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'instrument_id', name='uq_watchlist_instrument')
    )
    op.create_index(op.f('ix_watchlist_items_instrument_id'), 'watchlist_items', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('subject_date', sa.Date(), nullable=True),
    sa.Column('job_item_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_item_id'], ['job_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_kind_date_status', 'analysis_runs', ['kind', 'subject_date', 'status'], unique=False)
    op.create_index(op.f('ix_analysis_runs_instrument_id'), 'analysis_runs', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_kind'), 'analysis_runs', ['kind'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_runs_subject_date'), 'analysis_runs', ['subject_date'], unique=False)
    op.create_table('watchlist_item_tags',
    sa.Column('watchlist_item_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_item_id', 'tag_id')
    )
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_analysis_run_id'), 'analysis_reports', ['analysis_run_id'], unique=False)
    op.create_table('limit_up_metrics',
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('limit_up_event_id', sa.Integer(), nullable=False),
    sa.Column('day_score', sa.Float(), nullable=True),
    sa.Column('week_score', sa.Float(), nullable=True),
    sa.Column('value_score', sa.Float(), nullable=True),
    sa.Column('market_score', sa.Float(), nullable=True),
    sa.Column('timing_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('day_classification', sa.String(length=32), nullable=True),
    sa.Column('week_classification', sa.String(length=32), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('risk_plan', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['limit_up_event_id'], ['limit_up_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_run_id')
    )
    op.create_index(op.f('ix_limit_up_metrics_limit_up_event_id'), 'limit_up_metrics', ['limit_up_event_id'], unique=False)
    op.create_index(op.f('ix_limit_up_metrics_overall_score'), 'limit_up_metrics', ['overall_score'], unique=False)
    op.create_table('radar_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_label', sa.String(length=32), nullable=False),
    sa.Column('executable_position', sa.Float(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'algorithm_version', name='uq_radar_date_version')
    )
    op.create_index('ix_radar_date_version', 'radar_snapshots', ['trade_date', 'algorithm_version'], unique=False)
    op.create_index(op.f('ix_radar_snapshots_status'), 'radar_snapshots', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radar_snapshots_status'), table_name='radar_snapshots')
    op.drop_index('ix_radar_date_version', table_name='radar_snapshots')
    op.drop_table('radar_snapshots')
    op.drop_index(op.f('ix_limit_up_metrics_overall_score'), table_name='limit_up_metrics')
    op.drop_index(op.f('ix_limit_up_metrics_limit_up_event_id'), table_name='limit_up_metrics')
    op.drop_table('limit_up_metrics')
    op.drop_index(op.f('ix_analysis_reports_analysis_run_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_table('watchlist_item_tags')
    op.drop_index(op.f('ix_analysis_runs_subject_date'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_kind'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_instrument_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_kind_date_status', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_instrument_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_scan_results_signal_type'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_signal_date'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_kind'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_job_id'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_instrument_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_limit_up_events_trade_date'), table_name='limit_up_events')
    op.drop_index(op.f('ix_limit_up_events_quarantined'), table_name='limit_up_events')
    op.drop_index(op.f('ix_limit_up_events_legacy_code'), table_name='limit_up_events')
    op.drop_index(op.f('ix_limit_up_events_instrument_id'), table_name='limit_up_events')
    op.drop_table('limit_up_events')
    op.drop_index(op.f('ix_job_items_status'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_job_id'), table_name='job_items')
    op.drop_table('job_items')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_ipo_events_listing_date'), table_name='ipo_events')
    op.drop_index(op.f('ix_ipo_events_legacy_code'), table_name='ipo_events')
    op.drop_index(op.f('ix_ipo_events_instrument_id'), table_name='ipo_events')
    op.drop_table('ipo_events')
    op.drop_index('ix_bars_series_time', table_name='bars')
    op.drop_table('bars')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('secret_settings')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_requested_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_dedupe_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_index('ix_jobs_active_dedupe', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_instruments_ts_code'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_status'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_industry_id'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_exchange'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_code'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_area'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_kind'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('trading_calendar')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_table('industries')
    op.drop_table('data_sources')
    op.drop_table('automation_schedules')
    # ### end Alembic commands ###